# Generated by Django 5.1 on 2024-08-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=24, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('dob', models.DateField(null=True)),
                ('can_edit', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
