# Generated by Django 5.1 on 2024-08-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0002_alter_leader_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
