# Generated by Django 5.1 on 2024-08-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0003_alter_leader_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='leadersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=24)),
                ('profile_pic', models.ImageField(upload_to='media/uploads/images')),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=32)),
            ],
        ),
    ]
