# Generated by Django 5.1 on 2024-08-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bhulku',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=24)),
                ('middle_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=24)),
                ('standard', models.SmallIntegerField(null=True)),
                ('dob', models.DateField(null=True)),
                ('age', models.SmallIntegerField(null=True)),
                ('school', models.CharField(max_length=24, null=True)),
                ('address', models.CharField(max_length=24, null=True)),
            ],
        ),
    ]
