# Generated by Django 5.1 on 2024-08-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhulkus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhulku',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
