# Generated by Django 5.1 on 2024-08-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhulkus', '0002_alter_bhulku_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhulku',
            name='phone_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
