# Generated by Django 5.1 on 2024-08-18 14:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhulkus', '0003_bhulku_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhulku',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
