# Generated by Django 5.1 on 2024-08-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhulkus', '0004_alter_bhulku_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhulku',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
